const translations = {
  el: {
    navSupport: "Support",
    navPrivacy: "Privacy",
    navTerms: "Terms",
    heroEyebrow: "Invoice Management",
    heroTitle: "Δημιούργησε παραστατικά εύκολα.",
    heroLead: "Το myInvoice σε βοηθά να δημιουργείς παραστατικά, να οργανώνεις πελάτες και να διαχειρίζεσαι την καθημερινή τιμολόγηση από iPhone, iPad και Mac.",
    heroSupport: "Υποστήριξη",
    heroPrivacy: "Privacy Policy",
    pillInvoices: "Παραστατικά",
    pillCustomers: "Πελάτες",
    pillVat: "ΑΦΜ Lookup",
    pillSync: "iCloud Sync",
    strip1Title: "Παραστατικά",
    strip1Text: "Δημιούργησε παραστατικά και έγγραφα γρήγορα.",
    strip2Title: "Πελάτες",
    strip2Text: "Οργάνωσε στοιχεία πελατών σε ένα σημείο.",
    strip3Title: "ΑΦΜ Lookup",
    strip3Text: "Αναζήτηση στοιχείων επιχείρησης με ΑΦΜ.",
    strip4Title: "iCloud Sync",
    strip4Text: "Συγχρονισμός στις Apple συσκευές σου.",
    whyEyebrow: "Why myInvoice",
    whyTitle: "Όλα όσα χρειάζεσαι για την καθημερινή τιμολόγηση.",
    whyText: "Σχεδιασμένο για μικρές επιχειρήσεις, επαγγελματίες και ομάδες που θέλουν απλή και γρήγορη διαχείριση παραστατικών.",
    check1: "Απλό και γρήγορο περιβάλλον",
    check2: "Πελάτες, παραστατικά και είδη οργανωμένα",
    check3: "Υποστήριξη για iPhone, iPad και Mac",
    check4: "Έτοιμο για επεκτάσεις και ERP integrations",
    featuresEyebrow: "Features",
    featuresTitle: "Χτισμένο για παραγωγική εργασία.",
    card1Title: "Παραστατικά",
    card1Text: "Δημιούργησε, αναζήτησε και διαχειρίσου παραστατικά με καθαρή εικόνα.",
    card2Title: "Πελάτες",
    card2Text: "Κράτησε στοιχεία πελατών, ΑΦΜ, διευθύνσεις και επαφές.",
    card3Title: "Αναζήτηση ΑΦΜ",
    card3Text: "Συμπλήρωσε πιο γρήγορα στοιχεία επιχείρησης με αναζήτηση ΑΦΜ.",
    card4Title: "Συγχρονισμός",
    card4Text: "Δούλεψε σε διαφορετικές Apple συσκευές με συγχρονισμό δεδομένων.",
    card5Title: "Export & Share",
    card5Text: "Μοιράσου ή εξήγαγε έγγραφα όταν τα χρειάζεσαι.",
    card6Title: "ERP Ready",
    card6Text: "Σχεδιασμένο ώστε να υποστηρίξει μελλοντικές διασυνδέσεις με ERP.",
    faqTitle: "Συχνές ερωτήσεις",
    faq1Q: "Σε ποιες συσκευές λειτουργεί;",
    faq1A: "Το myInvoice έχει σχεδιαστεί για iPhone, iPad και Mac.",
    faq2Q: "Πού αποθηκεύονται τα δεδομένα;",
    faq2A: "Τα δεδομένα αποθηκεύονται στη συσκευή και μπορούν να συγχρονίζονται μέσω iCloud, αν είναι ενεργό.",
    faq3Q: "Υπάρχει υποστήριξη;",
    faq3A: "Ναι, μπορείς να επικοινωνήσεις μέσω της σελίδας Support.",
    ctaEyebrow: "Support",
    ctaTitle: "Χρειάζεσαι βοήθεια;",
    ctaText: "Επικοινώνησε μαζί μας για ερωτήσεις, υποστήριξη ή αναφορά προβλήματος.",
    ctaButton: "Get Support →",

    supportTitle: "Υποστήριξη myInvoice",
    supportLead: "Ευχαριστούμε που χρησιμοποιείς το myInvoice. Για ερωτήσεις, βοήθεια ή αναφορά προβλήματος, μπορείς να επικοινωνήσεις μαζί μας.",
    supportContact: "Επικοινωνία",
    supportTopicsTitle: "Συχνά θέματα",
    supportTopic1: "Δημιουργία και διαχείριση παραστατικών",
    supportTopic2: "Διαχείριση πελατών",
    supportTopic3: "Αναζήτηση στοιχείων με ΑΦΜ",
    supportTopic4: "Συγχρονισμός δεδομένων",
    supportTopic5: "Export ή αποστολή εγγράφων",
    supportResponseTitle: "Χρόνος απάντησης",
    supportResponseText: "Προσπαθούμε να απαντάμε όσο το δυνατόν πιο σύντομα.",

    lastUpdatedLabel: "Τελευταία ενημέρωση:",
    privacyTitle: "Πολιτική Απορρήτου",
    privacyIntro: "Το myInvoice είναι εφαρμογή διαχείρισης παραστατικών και πελατών. Η παρούσα Πολιτική Απορρήτου εξηγεί πώς διαχειρίζονται τα δεδομένα όταν χρησιμοποιείς την εφαρμογή.",
    privacyDataTitle: "Συλλογή δεδομένων",
    privacyDataText1: "Το myInvoice αποθηκεύει τις πληροφορίες που εισάγεις στην εφαρμογή, όπως πελάτες, παραστατικά, στοιχεία εγγράφων, στοιχεία επικοινωνίας και επαγγελματικά δεδομένα.",
    privacyDataText2: "Τα δεδομένα αποθηκεύονται τοπικά στη συσκευή σου και μπορούν να συγχρονίζονται μέσω Apple iCloud, αν ο συγχρονισμός iCloud είναι ενεργός.",
    privacyNoSell: "Δεν πουλάμε τα δεδομένα σου.",
    privacyThirdTitle: "Υπηρεσίες τρίτων",
    privacyThirdText: "Το myInvoice μπορεί να συνδέεται με εξωτερικές υπηρεσίες, όπως υπηρεσίες αναζήτησης ΑΦΜ ή ERP integrations, μόνο όταν επιλέγεις να χρησιμοποιήσεις αυτές τις λειτουργίες.",
    privacyUsageTitle: "Χρήση δεδομένων",
    privacyUsage1: "Δημιουργία και διαχείριση παραστατικών",
    privacyUsage2: "Διαχείριση πελατών",
    privacyUsage3: "Αναζήτηση επιχειρηματικών στοιχείων",
    privacyUsage4: "Συγχρονισμός δεδομένων στις συσκευές σου",
    privacyUsage5: "Αποστολή ή εξαγωγή εγγράφων",
    privacyRetentionTitle: "Διατήρηση και διαγραφή",
    privacyRetentionText: "Τα δεδομένα παραμένουν στη συσκευή ή στον iCloud λογαριασμό σου όσο τα διατηρείς. Μπορείς να τα διαγράψεις από την εφαρμογή ή αφαιρώντας την εφαρμογή από τις συσκευές σου.",
    privacyContactTitle: "Επικοινωνία",
    privacyContactText: "Για ερωτήσεις σχετικά με την Πολιτική Απορρήτου, επικοινώνησε στο:",

    termsTitle: "Όροι Χρήσης",
    termsIntro: "Χρησιμοποιώντας το myInvoice, συμφωνείς ότι η εφαρμογή παρέχεται για οργάνωση και διαχείριση παραστατικών και πελατών.",
    termsUseTitle: "Χρήση της εφαρμογής",
    termsUseText: "Είσαι υπεύθυνος για την ακρίβεια των δεδομένων που εισάγεις στην εφαρμογή, καθώς και για τη συμμόρφωση με τους φορολογικούς και επαγγελματικούς κανόνες που ισχύουν για εσένα.",
    termsAvailabilityTitle: "Διαθεσιμότητα",
    termsAvailabilityText: "Προσπαθούμε να διατηρούμε την εφαρμογή αξιόπιστη, αλλά δεν εγγυόμαστε αδιάλειπτη λειτουργία ή ότι όλες οι λειτουργίες θα είναι διαθέσιμες σε κάθε συσκευή ή περιοχή.",
    termsLiabilityTitle: "Περιορισμός ευθύνης",
    termsLiabilityText: "Το myInvoice παρέχεται “ως έχει”. Δεν φέρουμε ευθύνη για απώλειες ή ζημιές που μπορεί να προκύψουν από τη χρήση ή την αδυναμία χρήσης της εφαρμογής.",
    termsContactTitle: "Επικοινωνία",
    termsContactText: "Για ερωτήσεις σχετικά με τους Όρους Χρήσης, επικοινώνησε στο:"
  },

  en: {
    navSupport: "Support",
    navPrivacy: "Privacy",
    navTerms: "Terms",
    heroEyebrow: "Invoice Management",
    heroTitle: "Professional invoicing, made simple.",
    heroLead: "myInvoice helps you create invoices, organize customers, and manage your daily invoicing workflow from iPhone, iPad and Mac.",
    heroSupport: "Get Support",
    heroPrivacy: "Privacy Policy",
    pillInvoices: "Invoices",
    pillCustomers: "Customers",
    pillVat: "VAT Lookup",
    pillSync: "iCloud Sync",
    strip1Title: "Create Invoices",
    strip1Text: "Create invoices and documents quickly.",
    strip2Title: "Manage Customers",
    strip2Text: "Keep customer details in one place.",
    strip3Title: "VAT Number Lookup",
    strip3Text: "Look up company details by VAT number.",
    strip4Title: "iCloud Sync",
    strip4Text: "Sync across your Apple devices.",
    whyEyebrow: "Why myInvoice",
    whyTitle: "Everything you need for daily invoice management.",
    whyText: "Designed for small businesses, professionals, and teams that want simple and fast invoice management.",
    check1: "Simple and fast interface",
    check2: "Customers, documents and items organized",
    check3: "Support for iPhone, iPad and Mac",
    check4: "Ready for extensions and ERP integrations",
    featuresEyebrow: "Features",
    featuresTitle: "Built for productive work.",
    card1Title: "Invoices",
    card1Text: "Create, search and manage documents with a clear workflow.",
    card2Title: "Customers",
    card2Text: "Store customer details, VAT numbers, addresses and contacts.",
    card3Title: "VAT Lookup",
    card3Text: "Fill in business details faster using VAT number lookup.",
    card4Title: "Sync",
    card4Text: "Work across Apple devices with data synchronization.",
    card5Title: "Export & Share",
    card5Text: "Share or export documents whenever you need them.",
    card6Title: "ERP Ready",
    card6Text: "Designed to support future ERP integrations.",
    faqTitle: "Frequently asked questions",
    faq1Q: "Which devices are supported?",
    faq1A: "myInvoice is designed for iPhone, iPad and Mac.",
    faq2Q: "Where is my data stored?",
    faq2A: "Your data is stored on your device and can sync through iCloud when enabled.",
    faq3Q: "Is support available?",
    faq3A: "Yes, you can contact us through the Support page.",
    ctaEyebrow: "Support",
    ctaTitle: "Need help?",
    ctaText: "Contact us for questions, support, or issue reports.",
    ctaButton: "Get Support →",

    supportTitle: "myInvoice Support",
    supportLead: "Thank you for using myInvoice. If you need help, have a question, or want to report an issue, please contact us.",
    supportContact: "Contact",
    supportTopicsTitle: "Common topics",
    supportTopic1: "Creating and managing invoices",
    supportTopic2: "Managing customers",
    supportTopic3: "VAT number lookup",
    supportTopic4: "Data sync",
    supportTopic5: "Exporting or sharing documents",
    supportResponseTitle: "Response time",
    supportResponseText: "We usually respond as soon as possible.",

    lastUpdatedLabel: "Last updated:",
    privacyTitle: "Privacy Policy",
    privacyIntro: "myInvoice is an invoice and customer management app. This Privacy Policy explains how data is handled when you use the app.",
    privacyDataTitle: "Data Collection",
    privacyDataText1: "myInvoice stores the information you enter in the app, such as customers, invoices, document details, contact information, and business-related data.",
    privacyDataText2: "This data is stored locally on your device and may be synced through Apple iCloud if iCloud sync is enabled.",
    privacyNoSell: "We do not sell your data.",
    privacyThirdTitle: "Third-Party Services",
    privacyThirdText: "myInvoice may connect to external services such as VAT number lookup services or ERP integrations, only when you choose to use these features.",
    privacyUsageTitle: "Data Usage",
    privacyUsage1: "Creating and managing invoices",
    privacyUsage2: "Managing customers",
    privacyUsage3: "Searching business details",
    privacyUsage4: "Syncing data across your devices",
    privacyUsage5: "Sending or exporting documents",
    privacyRetentionTitle: "Data Retention and Deletion",
    privacyRetentionText: "Data remains on your device or in your iCloud account for as long as you keep it. You can delete your data from the app or by deleting the app from your devices.",
    privacyContactTitle: "Contact",
    privacyContactText: "If you have questions about this Privacy Policy, contact us at:",

    termsTitle: "Terms of Use",
    termsIntro: "By using myInvoice, you agree that the app is provided for organizing and managing invoices and customers.",
    termsUseTitle: "Use of the App",
    termsUseText: "You are responsible for the accuracy of the data you enter in the app and for complying with tax and professional rules that apply to you.",
    termsAvailabilityTitle: "Availability",
    termsAvailabilityText: "We try to keep the app reliable, but we do not guarantee uninterrupted operation or that every feature will be available on every device or region.",
    termsLiabilityTitle: "Limitation of Liability",
    termsLiabilityText: "myInvoice is provided “as is”. We are not responsible for losses or damages that may result from using or being unable to use the app.",
    termsContactTitle: "Contact",
    termsContactText: "If you have questions about these Terms of Use, contact us at:"
  }
};

function setLanguage(lang) {
  const dictionary = translations[lang] || translations.el;
  document.documentElement.lang = lang;

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.getAttribute("data-i18n");
    if (dictionary[key]) {
      element.textContent = dictionary[key];
    }
  });

  document.querySelectorAll("[data-lang]").forEach((button) => {
    button.classList.toggle("active", button.getAttribute("data-lang") === lang);
  });

  localStorage.setItem("myinvoice-language", lang);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => {
    setLanguage(button.getAttribute("data-lang"));
  });
});

const savedLang = localStorage.getItem("myinvoice-language");
const browserLang = navigator.language && navigator.language.toLowerCase().startsWith("el") ? "el" : "en";
setLanguage(savedLang || browserLang);
